---

version: "3.3"

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: "mohamedlavu/docker-nginx:latest"
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: "mohamedlavu/docker-php8:latest"
    container_name: php
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet
    ports:
      - 6379:6379
      - 6001:6001
    environment:
      - REDIS_REPLICATION_MODE=master
    depends_on:
      - nginx

  reactjs:
    build:
      context: ./pro-chat
      dockerfile: Dockerfile
    container_name: reactjs
    ports:
      - 3000:3000
    networks:
      - appnet
    depends_on:
      - nginx

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3308:3308"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql:/var/lib/mysql-files
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "9090:80"
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"

#Volumes
volumes:
  dbdata:
    driver: local
