# Use an official Node runtime as a parent image
FROM node:20-alpine

# Get the latest version of Playwright
FROM mcr.microsoft.com/playwright:focal


# Set Playwright browser path
ENV PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright

# Create a directory for the app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# install all dependencies
RUN npm install --frozen-lockfile --legacy-peer-deps

# Install Playwright
RUN apt-get update && apt-get -y install libnss3 libatk-bridge2.0-0 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libatspi2.0-0 libxshmfence-dev

# Install only chromium and run tests in headless mode
RUN npx playwright install chromium

# Copy the rest of the app to the container
COPY . .

# Expose ports for Next.js and Storybook
EXPOSE 5000 6006 9323

CMD ["sh", "./start.sh"]