import type { Metadata } from "next";
import "./globals.css";
import { StoreProvider } from "@/providers/store-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import DarkSwitch from "@/components/master/layout/DarkSwitch";

export const metadata: Metadata = {
  title: "Chat Application",
  description: "Generated by shadcn",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <DarkSwitch />
            {children}
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
